version: "3"

services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3:latest
    ports:
      - "8081:8081"
      - "8082:8082"
    networks:
      - repository

networks:
  repository:
    driver: bridge
